### ISSUE TITLE
Got error when build on version 0.5.6

### ISSUE THREAD

**Issue by pkasidit** [iminsoftware/imin_printer#7]
Hi Teams,

I got the error on version 0.5.6 as below.

imin_printer-0.5.6/android/src/main/java/com/imin/printer/imin_printer/IminPrinterPlugin.java:532: error: cannot find symbol
                   iminPrintUtils.openCashBox();

Thanks

**Comment by iminsoftware** [comment]
use old version [0.5.5](https://pub.dev/packages/imin_printer/versions/0.5.5)  openCashBox method Some issues will be addressed in the next release
